apiVersion: v1
kind: Pod
metadata:
  name: mpi-runner
spec:
  containers:
  - name: cnt
    command:
    - bash
    - -c
    - "python3 ./exec/runner/runner.py"
    image: "image-registry.openshift-image-registry.svc:5000/mpi-benchmarking/mpi-bench:runner"
    imagePullPolicy: Always
    env:
    - name: CMD_FROM_RUNNER
      value: "/workload/exec/run_benchmark.sh"
    - name: ARGS_FROM_RUNNER
      value: "run=1 cloud=aws machine=m5.2xlarge network=SDN mode=p2p operation=latency"
    - name: KUBECONFIG
      value: /etc/kubeconfig/kubeconfig
    volumeMounts:
    - mountPath: /etc/kubeconfig
      name: kubeconfig-secret
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: kubeconfig-secret
    # oc create secret generic kubeconfig-secret --from-file $KUBECONFIG
    secret:
      secretName: kubeconfig-secret
